### ISSUE TITLE
Error, help

### ISSUE THREAD

**Issue by cholinkol** [wallace11/ulauncher-url-shortener#1]
Hey, can you please repairt this: "Unexpected API error. KeyError: com.github.wallace11.ulauncher-url-shortener"

**Comment by wallace11** [comment]
Hi,
Where and when exactly do you get this error?
Please elaborate.

**Comment by ivashin** [comment]
@kevinko12323 I had the same issue. Installing required python package `pip install requests` resolved it. 

Please note that you need to install it for Python 2. In my case, I had pip only for Python 3, so had to install `python-pip` first, then used `pip2 install requests`.

**Comment by cholinkol** [comment]
> @kevinko12323 I had the same issue. Installing required python package `pip install requests` resolved it.
> 
> Please note that you need to install it for Python 2. In my case, I had pip only for Python 3, so had to install `python-pip` first, then used `pip2 install requests`.

Hello, sorry I did not write off for a long time, thank you to solve the problem :)
