### ISSUE TITLE
Slyme is shut down

### ISSUE THREAD

**Issue by ivashin** [wallace11/ulauncher-url-shortener#2]
As per https://5ly.me/
> Slyme was shut down over concerns of increasing spam and phlishing links on the platform

It makes sense to consider using another service for URL shortening. [is.gd](https://is.gd/apishorteningreference.php) seems like a reasonable alternative.

**Comment by wallace11** [comment]
Thanks for the heads up and suggestion for a new platform.
I'll take a look at that as soon as I can.
